markdown: kramdown
test_unit_version: 3.2.7
test_unit_release_date: 2017-12-12
test_unit_rails_version: 5.0.5
test_unit_rails_release_date: 2016-12-20
test_unit_activesupport_version: 1.0.8
test_unit_activesupport_release_date: 2016-12-20
test_unit_full_version: 0.0.5
test_unit_full_release_date: 2016-10-16

kramdown:
  enable_rouge: true
