markdown: kramdown
test_unit_version: 3.2.1
test_unit_release_date: 2016-06-12
test_unit_rails_version: 5.0.1
test_unit_rails_release_date: 2016-02-27
test_unit_activesupport_version: 1.0.6
test_unit_activesupport_release_date: 2016-05-20

kramdown:
  enable_rouge: true
